name: Deployment Workflow
on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string


runs:
  using: composite
  steps:
    - uses: ./.github/workflows/main_workflow/terraform_setup
      with:
        aws_region: ${{ matrix.aws_region }}

    - uses: ./.github/workflows/main_workflow/terraform_apply
      with:
        aws_region: ${{ matrix.aws_region }}      

    - uses: ./.github/workflows/main_workflow/deploy_application
      with:
        aws_region: ${{ matrix.aws_region }}

    - uses: ./.github/workflows/main_workflow/terraform_destroy
      with:
        aws_region: ${{ matrix.aws_region }}      