name: Terraform Destroy
on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      TF_API_TOKEN:
        required: true
        type: string

runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace AWS Region
        run: |
            sed -i 's/###AWS_REGION###/${{ inputs.aws_region }}/g' terraform/variables.tf
            sed -i 's/###TERRAFORM_CLOUD_WORKSPACE###/frontend-${{ inputs.aws_region }}/g' terraform/providers.tf
            pwd
            ls -latr
            sed -i 's/###AWS_REGION###/${{ inputs.aws_region }}/g' frontend/build/index.html
        shell: bash

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ inputs.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: cd terraform && terraform init
        shell: bash

      - name: Terraform Destroy
        run: cd terraform && terraform destroy -auto-approve  
        shell: bash        