name: Terraform Destroy
on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      TF_API_TOKEN:
        required: true
        type: string

runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace AWS Region
        run:  cd terraform && sed -i 's/###AWS_REGION###/${{ env.AWS_REGION }}/g' variables.tf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ inputs.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: cd terraform && terraform init

      - name: Terraform Destroy
        run: cd terraform && terraform destroy -auto-approve          