name: Destroy Application Workflow
on: [push]
jobs:

  call_destroy_application_workflow:
    runs-on: ubuntu-latest
    environment:
      name: dissertation-frontend
    strategy:
      max-parallel: 1
      matrix:
        aws_region: ["us-east-1", us-east-2]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: test
        run: pwd && ls -latr

      - uses: ./.github/workflows/destroy_application_workflow
        with:
          aws_region: ${{ matrix.aws_region }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    