name: Destroy Application Workflow
on: [push]
jobs:

  should_destroy_frontend:
    runs-on: ubuntu-latest
    environment:
      name: dissertation-frontend
    steps:
      - name: Should destroy frontend?
        run: echo "Should destroy frontend?"

  call_destroy_application_workflow:
    runs-on: ubuntu-latest
    needs: should_destroy_frontend
    strategy:
      max-parallel: 1
      matrix:
        aws_region: 
["us-east-1","us-east-2","us-west-1","us-west-2","eu-west-1","eu-west-2","eu-west-3","eu-south-1","eu-north-1","ap-northeast-1","ap-northeast-2","ap-northeast-3","ap-southeast-1","ap-southeast-2","ap-south-1","ca-central-1","eu-central-1","sa-east-1"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Output Current Directory
        run: pwd && ls -latr

      - name: Destroy the application workflow
        uses: ./.github/workflows/destroy_application_workflow
        with:
          aws_region: ${{ matrix.aws_region }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    